# Generated by Django 2.1.3 on 2018-12-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('recipes', 'Recipes'), ('maintenance', 'Maintenance')], default='fitness', max_length=15),
        ),
    ]
