# Generated by Django 2.1.3 on 2018-12-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogprofile', '0001_initial'),
        ('blog', '0003_auto_20181203_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='blogprofile.BlogProfile'),
        ),
    ]
